apiVersion: v1
kind: Service
metadata:
  name: blog-app-db
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: blog-app-db
  ports:
    - port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
