apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-app-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: blog-app-frontend
    app.kubernetes.io/part-of: blog-app
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.replicaCount.frontend }}
  selector:
    matchLabels:
      app.kubernetes.io/name: blog-app-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: blog-app-frontend
        app.kubernetes.io/part-of: blog-app
        app.kubernetes.io/component: frontend
    spec:
      automountServiceAccountToken: false
      containers:
        - name: frontend
          image: "{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}"
          imagePullPolicy: {{ .Values.image.frontend.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
          resources:
            requests:
              cpu: {{ .Values.resources.frontend.requests.cpu }}
              memory: {{ .Values.resources.frontend.requests.memory }}
            limits:
              cpu: {{ .Values.resources.frontend.limits.cpu }}
              memory: {{ .Values.resources.frontend.limits.memory }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 101
            capabilities:
              drop: ["ALL"]
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.containerPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.containerPort }}
