apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: blog-app-db-allow-backend-only
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: blog-app-db
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: blog-app-backend
      ports:
        - port: {{ .Values.db.port }}

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: blog-app-backend-allow-frontend-only
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: blog-app-backend
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: blog-app-frontend
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - port: {{ .Values.backend.port }}
