apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-app-db-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/part-of: blog-app
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.db.storageClassName }}
  storageClassName: {{ .Values.db.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.db.storage }}
