apiVersion: v1
kind: Secret
metadata:
  name: blog-app-db-secret
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/part-of: blog-app
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.db.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.db.password | quote }}
  POSTGRES_DB: {{ .Values.db.name | quote }}
